### ISSUE TITLE
About the part of single person(Can I get the humman dataset? The link is broken)

### ISSUE THREAD

**Issue by 021108** [openxrlab/xrmocap#116]
I want to get the humman dataset. And build the single person

**Comment by LazyBusyYang** [comment]
Sorry, humman dataset v0.1 version is currently unavailable due to the release of the humman dataset v1.0. The new dataset format is not yet supported by XRMoCap, but we are working it. If you are interested in v1.0, you can download it through [this link](https://caizhongang.github.io/projects/HuMMan/).

**Comment by LazyBusyYang** [comment]
The issue you mentioned will be addressed in https://github.com/openxrlab/xrmocap/pull/117.

**Comment by LazyBusyYang** [comment]
https://github.com/openxrlab/xrmocap/pull/117 has been merged.
