### ISSUE TITLE
Experiments about human3.6M

### ISSUE THREAD

**Issue by wangjiongw** [openxrlab/xrmocap#45]
hello, thanks for your excellent project. I wonder whether the multi-view motion capture with human3.6M will be supported? e.g. did you train MvP on Human3.6m dataset?
Thanks for your attention

**Comment by wqyin** [comment]
Hello, as Human3.6M is a multi-view single-person dataset, it is supported with our [single person pipeline](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#single-person). You may refer to the [prepare data tool instruction](https://github.com/openxrlab/xrmocap/blob/main/docs/en/tools/prepare_dataset.md) to get Human3.6M data ready.

We did not train MvP on Human3.6M since the method was designed for multi-person scenarios. However, we believe it can work on single-person scenes as well. You may train the model with [`n_instance`](https://github.com/openxrlab/xrmocap/blob/main/configs/mvp/shelf_config/mvp_shelf.py#:~:text=__dataset_n_kps__%20%3D%2014-,__n_instance__%20%3D%2010,-__n_cameras__%20%3D%205) set to a lower value to restrict the number of output persons from the network.
